import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import { ActionsProvider } from "./contexts/actions";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ActionsProvider>
			<html lang="en">
				<body
					className={`sans ${inter.className} ${roboto.className} flex items-center justify-center h-screen bg-gradient-to-r from-sky-100 to-indigo-200`}
				>
					{children}
				</body>
			</html>
		</ActionsProvider>
	);
}
